with-expecter: True
packages:
  github.com/Udean777/uang-bijak-go/internal/repository:
    interfaces:
      UserRepository:
      CategoryRepository:
      WalletRepository:
    output: ./internal/repository/mocks

  github.com/Udean777/uang-bijak-go/internal/service:
    interfaces:
      AuthService:
      UserService:
      CategoryService:
      WalletService:
    output: ./internal/service/mocks