// Code generated by mockery v2.53.5. DO NOT EDIT.

package repository

import (
	context "context"

	models "github.com/Udean777/uang-bijak-go/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCategoryRepository is an autogenerated mock type for the CategoryRepository type
type MockCategoryRepository struct {
	mock.Mock
}

type MockCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryRepository) EXPECT() *MockCategoryRepository_Expecter {
	return &MockCategoryRepository_Expecter{mock: &_m.Mock}
}

// CheckOwnership provides a mock function with given fields: ctx, categoryID, userID
func (_m *MockCategoryRepository) CheckOwnership(ctx context.Context, categoryID int64, userID uuid.UUID) (*models.Category, error) {
	ret := _m.Called(ctx, categoryID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CheckOwnership")
	}

	var r0 *models.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) (*models.Category, error)); ok {
		return rf(ctx, categoryID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) *models.Category); ok {
		r0 = rf(ctx, categoryID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, uuid.UUID) error); ok {
		r1 = rf(ctx, categoryID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_CheckOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckOwnership'
type MockCategoryRepository_CheckOwnership_Call struct {
	*mock.Call
}

// CheckOwnership is a helper method to define mock.On call
//   - ctx context.Context
//   - categoryID int64
//   - userID uuid.UUID
func (_e *MockCategoryRepository_Expecter) CheckOwnership(ctx interface{}, categoryID interface{}, userID interface{}) *MockCategoryRepository_CheckOwnership_Call {
	return &MockCategoryRepository_CheckOwnership_Call{Call: _e.mock.On("CheckOwnership", ctx, categoryID, userID)}
}

func (_c *MockCategoryRepository_CheckOwnership_Call) Run(run func(ctx context.Context, categoryID int64, userID uuid.UUID)) *MockCategoryRepository_CheckOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockCategoryRepository_CheckOwnership_Call) Return(_a0 *models.Category, _a1 error) *MockCategoryRepository_CheckOwnership_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_CheckOwnership_Call) RunAndReturn(run func(context.Context, int64, uuid.UUID) (*models.Category, error)) *MockCategoryRepository_CheckOwnership_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, category
func (_m *MockCategoryRepository) Create(ctx context.Context, category *models.Category) (int64, error) {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Category) (int64, error)); ok {
		return rf(ctx, category)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Category) int64); ok {
		r0 = rf(ctx, category)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Category) error); ok {
		r1 = rf(ctx, category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCategoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - category *models.Category
func (_e *MockCategoryRepository_Expecter) Create(ctx interface{}, category interface{}) *MockCategoryRepository_Create_Call {
	return &MockCategoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, category)}
}

func (_c *MockCategoryRepository_Create_Call) Run(run func(ctx context.Context, category *models.Category)) *MockCategoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Category))
	})
	return _c
}

func (_c *MockCategoryRepository_Create_Call) Return(_a0 int64, _a1 error) *MockCategoryRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Category) (int64, error)) *MockCategoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCategoryRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCategoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockCategoryRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockCategoryRepository_Delete_Call {
	return &MockCategoryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCategoryRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockCategoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockCategoryRepository_Delete_Call) Return(_a0 error) *MockCategoryRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockCategoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByUserID provides a mock function with given fields: ctx, userID
func (_m *MockCategoryRepository) GetAllByUserID(ctx context.Context, userID uuid.UUID) ([]models.Category, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUserID")
	}

	var r0 []models.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Category, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Category); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_GetAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByUserID'
type MockCategoryRepository_GetAllByUserID_Call struct {
	*mock.Call
}

// GetAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCategoryRepository_Expecter) GetAllByUserID(ctx interface{}, userID interface{}) *MockCategoryRepository_GetAllByUserID_Call {
	return &MockCategoryRepository_GetAllByUserID_Call{Call: _e.mock.On("GetAllByUserID", ctx, userID)}
}

func (_c *MockCategoryRepository_GetAllByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCategoryRepository_GetAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCategoryRepository_GetAllByUserID_Call) Return(_a0 []models.Category, _a1 error) *MockCategoryRepository_GetAllByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_GetAllByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.Category, error)) *MockCategoryRepository_GetAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockCategoryRepository) GetByID(ctx context.Context, id int64) (*models.Category, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.Category, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Category); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCategoryRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockCategoryRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockCategoryRepository_GetByID_Call {
	return &MockCategoryRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCategoryRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockCategoryRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockCategoryRepository_GetByID_Call) Return(_a0 *models.Category, _a1 error) *MockCategoryRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*models.Category, error)) *MockCategoryRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, name
func (_m *MockCategoryRepository) Update(ctx context.Context, id int64, name string) error {
	ret := _m.Called(ctx, id, name)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, id, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCategoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - name string
func (_e *MockCategoryRepository_Expecter) Update(ctx interface{}, id interface{}, name interface{}) *MockCategoryRepository_Update_Call {
	return &MockCategoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, name)}
}

func (_c *MockCategoryRepository_Update_Call) Run(run func(ctx context.Context, id int64, name string)) *MockCategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockCategoryRepository_Update_Call) Return(_a0 error) *MockCategoryRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryRepository_Update_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockCategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCategoryRepository creates a new instance of MockCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryRepository {
	mock := &MockCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
