// Code generated by mockery v2.53.5. DO NOT EDIT.

package repository

import (
	context "context"

	models "github.com/Udean777/uang-bijak-go/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockWalletRepository is an autogenerated mock type for the WalletRepository type
type MockWalletRepository struct {
	mock.Mock
}

type MockWalletRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletRepository) EXPECT() *MockWalletRepository_Expecter {
	return &MockWalletRepository_Expecter{mock: &_m.Mock}
}

// CheckOwnership provides a mock function with given fields: ctx, walletID, userID
func (_m *MockWalletRepository) CheckOwnership(ctx context.Context, walletID int64, userID uuid.UUID) (*models.Wallet, error) {
	ret := _m.Called(ctx, walletID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CheckOwnership")
	}

	var r0 *models.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) (*models.Wallet, error)); ok {
		return rf(ctx, walletID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) *models.Wallet); ok {
		r0 = rf(ctx, walletID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, uuid.UUID) error); ok {
		r1 = rf(ctx, walletID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepository_CheckOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckOwnership'
type MockWalletRepository_CheckOwnership_Call struct {
	*mock.Call
}

// CheckOwnership is a helper method to define mock.On call
//   - ctx context.Context
//   - walletID int64
//   - userID uuid.UUID
func (_e *MockWalletRepository_Expecter) CheckOwnership(ctx interface{}, walletID interface{}, userID interface{}) *MockWalletRepository_CheckOwnership_Call {
	return &MockWalletRepository_CheckOwnership_Call{Call: _e.mock.On("CheckOwnership", ctx, walletID, userID)}
}

func (_c *MockWalletRepository_CheckOwnership_Call) Run(run func(ctx context.Context, walletID int64, userID uuid.UUID)) *MockWalletRepository_CheckOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockWalletRepository_CheckOwnership_Call) Return(_a0 *models.Wallet, _a1 error) *MockWalletRepository_CheckOwnership_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepository_CheckOwnership_Call) RunAndReturn(run func(context.Context, int64, uuid.UUID) (*models.Wallet, error)) *MockWalletRepository_CheckOwnership_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, wallet
func (_m *MockWalletRepository) Create(ctx context.Context, wallet *models.Wallet) (int64, error) {
	ret := _m.Called(ctx, wallet)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Wallet) (int64, error)); ok {
		return rf(ctx, wallet)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Wallet) int64); ok {
		r0 = rf(ctx, wallet)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Wallet) error); ok {
		r1 = rf(ctx, wallet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWalletRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - wallet *models.Wallet
func (_e *MockWalletRepository_Expecter) Create(ctx interface{}, wallet interface{}) *MockWalletRepository_Create_Call {
	return &MockWalletRepository_Create_Call{Call: _e.mock.On("Create", ctx, wallet)}
}

func (_c *MockWalletRepository_Create_Call) Run(run func(ctx context.Context, wallet *models.Wallet)) *MockWalletRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Wallet))
	})
	return _c
}

func (_c *MockWalletRepository_Create_Call) Return(_a0 int64, _a1 error) *MockWalletRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Wallet) (int64, error)) *MockWalletRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockWalletRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWalletRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockWalletRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockWalletRepository_Delete_Call {
	return &MockWalletRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockWalletRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockWalletRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockWalletRepository_Delete_Call) Return(_a0 error) *MockWalletRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockWalletRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByUserID provides a mock function with given fields: ctx, userID
func (_m *MockWalletRepository) GetAllByUserID(ctx context.Context, userID uuid.UUID) ([]models.Wallet, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUserID")
	}

	var r0 []models.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Wallet, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Wallet); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepository_GetAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByUserID'
type MockWalletRepository_GetAllByUserID_Call struct {
	*mock.Call
}

// GetAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockWalletRepository_Expecter) GetAllByUserID(ctx interface{}, userID interface{}) *MockWalletRepository_GetAllByUserID_Call {
	return &MockWalletRepository_GetAllByUserID_Call{Call: _e.mock.On("GetAllByUserID", ctx, userID)}
}

func (_c *MockWalletRepository_GetAllByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockWalletRepository_GetAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockWalletRepository_GetAllByUserID_Call) Return(_a0 []models.Wallet, _a1 error) *MockWalletRepository_GetAllByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepository_GetAllByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.Wallet, error)) *MockWalletRepository_GetAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockWalletRepository) GetByID(ctx context.Context, id int64) (*models.Wallet, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.Wallet, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Wallet); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockWalletRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockWalletRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockWalletRepository_GetByID_Call {
	return &MockWalletRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockWalletRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockWalletRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockWalletRepository_GetByID_Call) Return(_a0 *models.Wallet, _a1 error) *MockWalletRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*models.Wallet, error)) *MockWalletRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, name
func (_m *MockWalletRepository) Update(ctx context.Context, id int64, name string) error {
	ret := _m.Called(ctx, id, name)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, id, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockWalletRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - name string
func (_e *MockWalletRepository_Expecter) Update(ctx interface{}, id interface{}, name interface{}) *MockWalletRepository_Update_Call {
	return &MockWalletRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, name)}
}

func (_c *MockWalletRepository_Update_Call) Run(run func(ctx context.Context, id int64, name string)) *MockWalletRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockWalletRepository_Update_Call) Return(_a0 error) *MockWalletRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletRepository_Update_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockWalletRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletRepository creates a new instance of MockWalletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletRepository {
	mock := &MockWalletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
