// Code generated by mockery v2.53.5. DO NOT EDIT.

package repository

import (
	context "context"

	models "github.com/Udean777/uang-bijak-go/internal/models"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	uuid "github.com/google/uuid"
)

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// CreateTx provides a mock function with given fields: ctx, tx, transaction
func (_m *MockTransactionRepository) CreateTx(ctx context.Context, tx pgx.Tx, transaction *models.Transaction) error {
	ret := _m.Called(ctx, tx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for CreateTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, *models.Transaction) error); ok {
		r0 = rf(ctx, tx, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionRepository_CreateTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTx'
type MockTransactionRepository_CreateTx_Call struct {
	*mock.Call
}

// CreateTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - transaction *models.Transaction
func (_e *MockTransactionRepository_Expecter) CreateTx(ctx interface{}, tx interface{}, transaction interface{}) *MockTransactionRepository_CreateTx_Call {
	return &MockTransactionRepository_CreateTx_Call{Call: _e.mock.On("CreateTx", ctx, tx, transaction)}
}

func (_c *MockTransactionRepository_CreateTx_Call) Run(run func(ctx context.Context, tx pgx.Tx, transaction *models.Transaction)) *MockTransactionRepository_CreateTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgx.Tx), args[2].(*models.Transaction))
	})
	return _c
}

func (_c *MockTransactionRepository_CreateTx_Call) Return(_a0 error) *MockTransactionRepository_CreateTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRepository_CreateTx_Call) RunAndReturn(run func(context.Context, pgx.Tx, *models.Transaction) error) *MockTransactionRepository_CreateTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByUserID provides a mock function with given fields: ctx, userID
func (_m *MockTransactionRepository) GetAllByUserID(ctx context.Context, userID uuid.UUID) ([]models.Transaction, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUserID")
	}

	var r0 []models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Transaction, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Transaction); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_GetAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByUserID'
type MockTransactionRepository_GetAllByUserID_Call struct {
	*mock.Call
}

// GetAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockTransactionRepository_Expecter) GetAllByUserID(ctx interface{}, userID interface{}) *MockTransactionRepository_GetAllByUserID_Call {
	return &MockTransactionRepository_GetAllByUserID_Call{Call: _e.mock.On("GetAllByUserID", ctx, userID)}
}

func (_c *MockTransactionRepository_GetAllByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockTransactionRepository_GetAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTransactionRepository_GetAllByUserID_Call) Return(_a0 []models.Transaction, _a1 error) *MockTransactionRepository_GetAllByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_GetAllByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.Transaction, error)) *MockTransactionRepository_GetAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
