// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	context "context"

	models "github.com/Udean777/uang-bijak-go/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockWalletService is an autogenerated mock type for the WalletService type
type MockWalletService struct {
	mock.Mock
}

type MockWalletService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletService) EXPECT() *MockWalletService_Expecter {
	return &MockWalletService_Expecter{mock: &_m.Mock}
}

// CreateWallet provides a mock function with given fields: ctx, req, userID
func (_m *MockWalletService) CreateWallet(ctx context.Context, req models.CreateWalletRequest, userID uuid.UUID) (*models.Wallet, error) {
	ret := _m.Called(ctx, req, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateWallet")
	}

	var r0 *models.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateWalletRequest, uuid.UUID) (*models.Wallet, error)); ok {
		return rf(ctx, req, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateWalletRequest, uuid.UUID) *models.Wallet); ok {
		r0 = rf(ctx, req, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateWalletRequest, uuid.UUID) error); ok {
		r1 = rf(ctx, req, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletService_CreateWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWallet'
type MockWalletService_CreateWallet_Call struct {
	*mock.Call
}

// CreateWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - req models.CreateWalletRequest
//   - userID uuid.UUID
func (_e *MockWalletService_Expecter) CreateWallet(ctx interface{}, req interface{}, userID interface{}) *MockWalletService_CreateWallet_Call {
	return &MockWalletService_CreateWallet_Call{Call: _e.mock.On("CreateWallet", ctx, req, userID)}
}

func (_c *MockWalletService_CreateWallet_Call) Run(run func(ctx context.Context, req models.CreateWalletRequest, userID uuid.UUID)) *MockWalletService_CreateWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CreateWalletRequest), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockWalletService_CreateWallet_Call) Return(_a0 *models.Wallet, _a1 error) *MockWalletService_CreateWallet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletService_CreateWallet_Call) RunAndReturn(run func(context.Context, models.CreateWalletRequest, uuid.UUID) (*models.Wallet, error)) *MockWalletService_CreateWallet_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWallet provides a mock function with given fields: ctx, walletID, userID
func (_m *MockWalletService) DeleteWallet(ctx context.Context, walletID int64, userID uuid.UUID) error {
	ret := _m.Called(ctx, walletID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWallet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) error); ok {
		r0 = rf(ctx, walletID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletService_DeleteWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWallet'
type MockWalletService_DeleteWallet_Call struct {
	*mock.Call
}

// DeleteWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - walletID int64
//   - userID uuid.UUID
func (_e *MockWalletService_Expecter) DeleteWallet(ctx interface{}, walletID interface{}, userID interface{}) *MockWalletService_DeleteWallet_Call {
	return &MockWalletService_DeleteWallet_Call{Call: _e.mock.On("DeleteWallet", ctx, walletID, userID)}
}

func (_c *MockWalletService_DeleteWallet_Call) Run(run func(ctx context.Context, walletID int64, userID uuid.UUID)) *MockWalletService_DeleteWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockWalletService_DeleteWallet_Call) Return(_a0 error) *MockWalletService_DeleteWallet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletService_DeleteWallet_Call) RunAndReturn(run func(context.Context, int64, uuid.UUID) error) *MockWalletService_DeleteWallet_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserWallets provides a mock function with given fields: ctx, userID
func (_m *MockWalletService) GetUserWallets(ctx context.Context, userID uuid.UUID) ([]models.Wallet, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserWallets")
	}

	var r0 []models.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Wallet, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Wallet); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWalletService_GetUserWallets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserWallets'
type MockWalletService_GetUserWallets_Call struct {
	*mock.Call
}

// GetUserWallets is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockWalletService_Expecter) GetUserWallets(ctx interface{}, userID interface{}) *MockWalletService_GetUserWallets_Call {
	return &MockWalletService_GetUserWallets_Call{Call: _e.mock.On("GetUserWallets", ctx, userID)}
}

func (_c *MockWalletService_GetUserWallets_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockWalletService_GetUserWallets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockWalletService_GetUserWallets_Call) Return(_a0 []models.Wallet, _a1 error) *MockWalletService_GetUserWallets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWalletService_GetUserWallets_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.Wallet, error)) *MockWalletService_GetUserWallets_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWallet provides a mock function with given fields: ctx, walletID, req, userID
func (_m *MockWalletService) UpdateWallet(ctx context.Context, walletID int64, req models.UpdateWalletRequest, userID uuid.UUID) error {
	ret := _m.Called(ctx, walletID, req, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWallet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.UpdateWalletRequest, uuid.UUID) error); ok {
		r0 = rf(ctx, walletID, req, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWalletService_UpdateWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWallet'
type MockWalletService_UpdateWallet_Call struct {
	*mock.Call
}

// UpdateWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - walletID int64
//   - req models.UpdateWalletRequest
//   - userID uuid.UUID
func (_e *MockWalletService_Expecter) UpdateWallet(ctx interface{}, walletID interface{}, req interface{}, userID interface{}) *MockWalletService_UpdateWallet_Call {
	return &MockWalletService_UpdateWallet_Call{Call: _e.mock.On("UpdateWallet", ctx, walletID, req, userID)}
}

func (_c *MockWalletService_UpdateWallet_Call) Run(run func(ctx context.Context, walletID int64, req models.UpdateWalletRequest, userID uuid.UUID)) *MockWalletService_UpdateWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(models.UpdateWalletRequest), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockWalletService_UpdateWallet_Call) Return(_a0 error) *MockWalletService_UpdateWallet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWalletService_UpdateWallet_Call) RunAndReturn(run func(context.Context, int64, models.UpdateWalletRequest, uuid.UUID) error) *MockWalletService_UpdateWallet_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWalletService creates a new instance of MockWalletService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletService {
	mock := &MockWalletService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
