// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	context "context"

	models "github.com/Udean777/uang-bijak-go/internal/models"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockDashboardService is an autogenerated mock type for the DashboardService type
type MockDashboardService struct {
	mock.Mock
}

type MockDashboardService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDashboardService) EXPECT() *MockDashboardService_Expecter {
	return &MockDashboardService_Expecter{mock: &_m.Mock}
}

// GetDashboardSummary provides a mock function with given fields: ctx, userID, startTime, endTime
func (_m *MockDashboardService) GetDashboardSummary(ctx context.Context, userID uuid.UUID, startTime time.Time, endTime time.Time) (*models.DashboardSummary, error) {
	ret := _m.Called(ctx, userID, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetDashboardSummary")
	}

	var r0 *models.DashboardSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) (*models.DashboardSummary, error)); ok {
		return rf(ctx, userID, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, time.Time) *models.DashboardSummary); ok {
		r0 = rf(ctx, userID, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DashboardSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDashboardService_GetDashboardSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDashboardSummary'
type MockDashboardService_GetDashboardSummary_Call struct {
	*mock.Call
}

// GetDashboardSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - startTime time.Time
//   - endTime time.Time
func (_e *MockDashboardService_Expecter) GetDashboardSummary(ctx interface{}, userID interface{}, startTime interface{}, endTime interface{}) *MockDashboardService_GetDashboardSummary_Call {
	return &MockDashboardService_GetDashboardSummary_Call{Call: _e.mock.On("GetDashboardSummary", ctx, userID, startTime, endTime)}
}

func (_c *MockDashboardService_GetDashboardSummary_Call) Run(run func(ctx context.Context, userID uuid.UUID, startTime time.Time, endTime time.Time)) *MockDashboardService_GetDashboardSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockDashboardService_GetDashboardSummary_Call) Return(_a0 *models.DashboardSummary, _a1 error) *MockDashboardService_GetDashboardSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDashboardService_GetDashboardSummary_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time, time.Time) (*models.DashboardSummary, error)) *MockDashboardService_GetDashboardSummary_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDashboardService creates a new instance of MockDashboardService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDashboardService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDashboardService {
	mock := &MockDashboardService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
