// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	context "context"

	models "github.com/Udean777/uang-bijak-go/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTransactionService is an autogenerated mock type for the TransactionService type
type MockTransactionService struct {
	mock.Mock
}

type MockTransactionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionService) EXPECT() *MockTransactionService_Expecter {
	return &MockTransactionService_Expecter{mock: &_m.Mock}
}

// CreateTransaction provides a mock function with given fields: ctx, req, userID
func (_m *MockTransactionService) CreateTransaction(ctx context.Context, req models.CreateTransactionRequest, userID uuid.UUID) (*models.Transaction, error) {
	ret := _m.Called(ctx, req, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateTransactionRequest, uuid.UUID) (*models.Transaction, error)); ok {
		return rf(ctx, req, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateTransactionRequest, uuid.UUID) *models.Transaction); ok {
		r0 = rf(ctx, req, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateTransactionRequest, uuid.UUID) error); ok {
		r1 = rf(ctx, req, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionService_CreateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransaction'
type MockTransactionService_CreateTransaction_Call struct {
	*mock.Call
}

// CreateTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - req models.CreateTransactionRequest
//   - userID uuid.UUID
func (_e *MockTransactionService_Expecter) CreateTransaction(ctx interface{}, req interface{}, userID interface{}) *MockTransactionService_CreateTransaction_Call {
	return &MockTransactionService_CreateTransaction_Call{Call: _e.mock.On("CreateTransaction", ctx, req, userID)}
}

func (_c *MockTransactionService_CreateTransaction_Call) Run(run func(ctx context.Context, req models.CreateTransactionRequest, userID uuid.UUID)) *MockTransactionService_CreateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CreateTransactionRequest), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockTransactionService_CreateTransaction_Call) Return(_a0 *models.Transaction, _a1 error) *MockTransactionService_CreateTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionService_CreateTransaction_Call) RunAndReturn(run func(context.Context, models.CreateTransactionRequest, uuid.UUID) (*models.Transaction, error)) *MockTransactionService_CreateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserTransactions provides a mock function with given fields: ctx, userID
func (_m *MockTransactionService) GetUserTransactions(ctx context.Context, userID uuid.UUID) ([]models.Transaction, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTransactions")
	}

	var r0 []models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Transaction, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Transaction); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionService_GetUserTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserTransactions'
type MockTransactionService_GetUserTransactions_Call struct {
	*mock.Call
}

// GetUserTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockTransactionService_Expecter) GetUserTransactions(ctx interface{}, userID interface{}) *MockTransactionService_GetUserTransactions_Call {
	return &MockTransactionService_GetUserTransactions_Call{Call: _e.mock.On("GetUserTransactions", ctx, userID)}
}

func (_c *MockTransactionService_GetUserTransactions_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockTransactionService_GetUserTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTransactionService_GetUserTransactions_Call) Return(_a0 []models.Transaction, _a1 error) *MockTransactionService_GetUserTransactions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionService_GetUserTransactions_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.Transaction, error)) *MockTransactionService_GetUserTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionService creates a new instance of MockTransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionService {
	mock := &MockTransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
