// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	context "context"

	models "github.com/Udean777/uang-bijak-go/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCategoryService is an autogenerated mock type for the CategoryService type
type MockCategoryService struct {
	mock.Mock
}

type MockCategoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryService) EXPECT() *MockCategoryService_Expecter {
	return &MockCategoryService_Expecter{mock: &_m.Mock}
}

// CreateCategory provides a mock function with given fields: ctx, req, userID
func (_m *MockCategoryService) CreateCategory(ctx context.Context, req models.UpsertCategoryRequest, userID uuid.UUID) (*models.Category, error) {
	ret := _m.Called(ctx, req, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 *models.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UpsertCategoryRequest, uuid.UUID) (*models.Category, error)); ok {
		return rf(ctx, req, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UpsertCategoryRequest, uuid.UUID) *models.Category); ok {
		r0 = rf(ctx, req, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UpsertCategoryRequest, uuid.UUID) error); ok {
		r1 = rf(ctx, req, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryService_CreateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCategory'
type MockCategoryService_CreateCategory_Call struct {
	*mock.Call
}

// CreateCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - req models.UpsertCategoryRequest
//   - userID uuid.UUID
func (_e *MockCategoryService_Expecter) CreateCategory(ctx interface{}, req interface{}, userID interface{}) *MockCategoryService_CreateCategory_Call {
	return &MockCategoryService_CreateCategory_Call{Call: _e.mock.On("CreateCategory", ctx, req, userID)}
}

func (_c *MockCategoryService_CreateCategory_Call) Run(run func(ctx context.Context, req models.UpsertCategoryRequest, userID uuid.UUID)) *MockCategoryService_CreateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UpsertCategoryRequest), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockCategoryService_CreateCategory_Call) Return(_a0 *models.Category, _a1 error) *MockCategoryService_CreateCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryService_CreateCategory_Call) RunAndReturn(run func(context.Context, models.UpsertCategoryRequest, uuid.UUID) (*models.Category, error)) *MockCategoryService_CreateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCategory provides a mock function with given fields: ctx, categoryID, userID
func (_m *MockCategoryService) DeleteCategory(ctx context.Context, categoryID int64, userID uuid.UUID) error {
	ret := _m.Called(ctx, categoryID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) error); ok {
		r0 = rf(ctx, categoryID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategoryService_DeleteCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCategory'
type MockCategoryService_DeleteCategory_Call struct {
	*mock.Call
}

// DeleteCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - categoryID int64
//   - userID uuid.UUID
func (_e *MockCategoryService_Expecter) DeleteCategory(ctx interface{}, categoryID interface{}, userID interface{}) *MockCategoryService_DeleteCategory_Call {
	return &MockCategoryService_DeleteCategory_Call{Call: _e.mock.On("DeleteCategory", ctx, categoryID, userID)}
}

func (_c *MockCategoryService_DeleteCategory_Call) Run(run func(ctx context.Context, categoryID int64, userID uuid.UUID)) *MockCategoryService_DeleteCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockCategoryService_DeleteCategory_Call) Return(_a0 error) *MockCategoryService_DeleteCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryService_DeleteCategory_Call) RunAndReturn(run func(context.Context, int64, uuid.UUID) error) *MockCategoryService_DeleteCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserCategories provides a mock function with given fields: ctx, userID
func (_m *MockCategoryService) GetUserCategories(ctx context.Context, userID uuid.UUID) ([]models.Category, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserCategories")
	}

	var r0 []models.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Category, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Category); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryService_GetUserCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserCategories'
type MockCategoryService_GetUserCategories_Call struct {
	*mock.Call
}

// GetUserCategories is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCategoryService_Expecter) GetUserCategories(ctx interface{}, userID interface{}) *MockCategoryService_GetUserCategories_Call {
	return &MockCategoryService_GetUserCategories_Call{Call: _e.mock.On("GetUserCategories", ctx, userID)}
}

func (_c *MockCategoryService_GetUserCategories_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCategoryService_GetUserCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCategoryService_GetUserCategories_Call) Return(_a0 []models.Category, _a1 error) *MockCategoryService_GetUserCategories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryService_GetUserCategories_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.Category, error)) *MockCategoryService_GetUserCategories_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCategory provides a mock function with given fields: ctx, categoryID, req, userID
func (_m *MockCategoryService) UpdateCategory(ctx context.Context, categoryID int64, req models.UpsertCategoryRequest, userID uuid.UUID) error {
	ret := _m.Called(ctx, categoryID, req, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.UpsertCategoryRequest, uuid.UUID) error); ok {
		r0 = rf(ctx, categoryID, req, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategoryService_UpdateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCategory'
type MockCategoryService_UpdateCategory_Call struct {
	*mock.Call
}

// UpdateCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - categoryID int64
//   - req models.UpsertCategoryRequest
//   - userID uuid.UUID
func (_e *MockCategoryService_Expecter) UpdateCategory(ctx interface{}, categoryID interface{}, req interface{}, userID interface{}) *MockCategoryService_UpdateCategory_Call {
	return &MockCategoryService_UpdateCategory_Call{Call: _e.mock.On("UpdateCategory", ctx, categoryID, req, userID)}
}

func (_c *MockCategoryService_UpdateCategory_Call) Run(run func(ctx context.Context, categoryID int64, req models.UpsertCategoryRequest, userID uuid.UUID)) *MockCategoryService_UpdateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(models.UpsertCategoryRequest), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockCategoryService_UpdateCategory_Call) Return(_a0 error) *MockCategoryService_UpdateCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryService_UpdateCategory_Call) RunAndReturn(run func(context.Context, int64, models.UpsertCategoryRequest, uuid.UUID) error) *MockCategoryService_UpdateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCategoryService creates a new instance of MockCategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryService {
	mock := &MockCategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
